spring:
  application:
    name: springdemo

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:h2:tcp:localhost/~/srpdemo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true


logging:
  level:
    root: info
